"""Initial migration.

Revision ID: 1
Revises: 
Create Date: 2025-11-24 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('pin_hash', sa.String(length=256), nullable=False),
    sa.Column('mpesa_balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(phone) >= 10', name='phone_length_check'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('recipient', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('is_fraudulent', sa.Boolean(), nullable=False),
    sa.Column('fraud_confidence', sa.Float(), nullable=False),
    sa.CheckConstraint('amount > 0', name='amount_positive'),
    sa.CheckConstraint('fraud_confidence >= 0.0 AND fraud_confidence <= 1.0', name='confidence_range'),
    sa.CheckConstraint('length(recipient) >= 10', name='recipient_length_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_is_fraudulent'), ['is_fraudulent'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_recipient'), ['recipient'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_transactions_recipient'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_fraudulent'))

    op.drop_table('transactions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    # ### end Alembic commands ###
