"""Add M-Pesa transaction models

Revision ID: 745c2f94b400
Revises: 
Create Date: 2025-11-18 15:19:49.872923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745c2f94b400'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=64), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=64), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('account_reference', sa.String(length=64), nullable=False),
    sa.Column('transaction_desc', sa.String(length=128), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=True),
    sa.Column('result_desc', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('callback_data', sa.Text(), nullable=True),
    sa.CheckConstraint('amount > 0', name='mpesa_amount_positive'),
    sa.CheckConstraint('length(phone_number) >= 10', name='mpesa_phone_length_check'),
    sa.CheckConstraint('status IN ("pending", "completed", "failed", "cancelled")', name='mpesa_status_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'), ['checkout_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_merchant_request_id'), ['merchant_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_mpesa_receipt_number'), ['mpesa_receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_phone_number'), ['phone_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_mpesa_transactions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_phone_number'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_mpesa_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_merchant_request_id'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_created_at'))
        batch_op.drop_index(batch_op.f('ix_mpesa_transactions_checkout_request_id'))

    op.drop_table('mpesa_transactions')
    # ### end Alembic commands ###
