"""Add user budget plans table.

Revision ID: b1c2d3e4f5g6
Revises: a8a1d2c2d3e4
Create Date: 2025-12-06 21:43:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c2d3e4f5g6'
down_revision = 'a8a1d2c2d3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_budget_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=128), nullable=False),
    sa.Column('plan_description', sa.Text(), nullable=True),
    sa.Column('monthly_income', sa.Float(), nullable=False),
    sa.Column('savings_goal', sa.Float(), nullable=True),
    sa.Column('savings_period_months', sa.Integer(), nullable=True),
    sa.Column('allocations', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('monthly_income > 0', name='income_positive'),
    sa.CheckConstraint('savings_goal >= 0', name='savings_goal_non_negative'),
    sa.CheckConstraint('savings_period_months > 0', name='savings_period_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_budget_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_budget_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_budget_plans_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_budget_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_budget_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_budget_plans_created_at'))

    op.drop_table('user_budget_plans')
    # ### end Alembic commands ###